### ISSUE TITLE
can you write a install docs ?

### ISSUE THREAD

**Issue by vistal8** [YehudaEi/Y-Link#1]
i hanve install the web but  is' You have error: Unknown error'

**Comment by JunLeB** [comment]
thakns

**Comment by YehudaEi** [comment]
happily,
I will try to write in the coming days.

Can you elaborate a little more on the error? (Apache logs, PHP logs, etc.)

**Comment by JunLeB** [comment]
> happily,
> I will try to write in the coming days.
> 
> Can you elaborate a little more on the error? (Apache logs, PHP logs, etc.)

hello  i use the nginx and php 7.1  the logs is no error but when use shor link button  it's  You have error: Unknown error'

**Comment by JunLeB** [comment]
> happily,
> I will try to write in the coming days.
> 
> Can you elaborate a little more on the error? (Apache logs, PHP logs, etc.)
the error page is down 
https://thumbsnap.com/X1A4tGCR

thanks

**Comment by JunLeB** [comment]
i find the problems,it must  open the  ssl   but  the nginx rewrite  can't be run

**Comment by YehudaEi** [comment]
Excellent, anyway I have already written the installation instructions and now I am just checking that they are ok and everything, I will probably upload them today.

**Comment by JunLeB** [comment]
> Excellent, anyway I have already written the installation instructions and now I am just checking that they are ok and everything, I will probably upload them today.


Thank you very much. Can you also provide nginx rewrite.

**Comment by YehudaEi** [comment]
I Added. Enjoy 😁

**Comment by JunLeB** [comment]
> I Added. Enjoy 😁

thanks  i like you
